---
name: Release

on:
  push:
    branches:
      - alpha
      - beta
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.gh_token}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install Packages
        run: npm ci
      - name: Publish
        run: npx semantic-release
        env:
          NODE_ENV: "cicd"
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.gh_token}}
          NPM_TOKEN: ${{ secrets.npm_token }}
          GIT_AUTHOR_NAME: "autocloud-deploy-bot"
          GIT_AUTHOR_EMAIL: "no-reply@autocloud.dev"
          GIT_COMMITTER_NAME: "autocloud-deploy-bot"
          GIT_COMMITTER_EMAIL: "no-reply@autocloud.dev"